# Analyzing representative cycles for persitent homology with Giotto-TDA

The goal of this notebook is to simplify the use of cycles for the analysis of persistent homology. We demonstrate their usage on a subset of the MNIST dataset. Moreover, we provide an overview of applications using the direct visualization of cycles for exploratory data analysis.


# 1. Introduction and Motivation

Information captured by persistent homology is commonly represented by a persistence diagram or, equivalently, a persistence barcode. 

These are elegant mathematical representations of the homology classes that appear and disappear in a filtration. However, their use for exploratory data analysis is challenging. While they effectively represent the lifespan of each homology class, they also lose connection with the original domain of data.  

This brings to two main problems:

1. we have no information regarding the distribution of persistence pairs in the original domain
2. we have no information regarding the shape of each homology class appearing in the filtration.

This means that interpreting the results becomes extremely difficult for a user. Experts in TDA may be able to guess this information by combaning persistence diagrams with a visualization of the original filtration. However, this is generally not an easy task, especially for newcomers. 

Questions like

- Is the filtration I am using correct?
- Are the homology classes appearing in my persistence diagram aligned with the features I see in the input data?

are quite natural when we start computing persistent homology on a new dataset. 


To be able to answer this type of questions we need to map information from the persistence diagram back to the original domain of the filtration. In this notebook, we provide a collection of functions to simplify the interactive visualization and analysis of homology class by enriching the information contained in the persistence diagram with cycles.

# 2. Analysis

## 2.1. Dataset description

![dataset](./pictures/dataset.png)

In the remainder of this notebook, we use part of the original MNIST dataset downloaded from [here](http://yann.lecun.com/exdb/mnist/). The dataset provided in this submission includes 500 handwritten digits (50 images per digit) that have been size-normalized and centered in a fixed-size image.


## 2.2. Preprocessing

The first step when using persistent homology is that of defining a filtration on the input data. This already provides a degree of freedom for users that may define the most suitable filtration based on the features they want to be highlighted.

For example, in the case of an MNIST digit we may want to highlight dominant cycles in the input digits. To this end, we may apply different filtrations:

- the one defined by the original grayscale image, 
- the inverse (negated) grayscale image,
- or new image obtained by applying the distance transform to the original image.

Clearly, each image will be transformed in a filtration generating different homology cycles and, consequently, different persistence diagrams. In this notebook, all filtrations are generated applying the distance transform to the input image, but any other filtrations could be used instead.

![filtrations](pictures/filtrations.png)
Images shown above are generated with `./scripts/filtrations.py`

### External tools

The computation of persistence diagrams and representative cycles has been implemented in a C++ [library](https://github.com/IuricichF/PersistenceCycles) integrated in the Topology Toolkit [(TTK)](https://topology-tool-kit.github.io). For simplicity, we have precomputed all persitence diagrams and all representative cycles with our external library and saved them in the folder `data/vtk-*/`. Due to the file limitation of the submission, we provide the full dataset [here](https://drive.google.com/drive/folders/14Z1UGhCiCtWOPYVbKWHW-InUvKbsZ3-H?usp=sharing), and only keep the necessary files in the repository.

## 2.3. Visualizying cycles

We import necessary Python packages.

In [1]:
import sys

# Check Python version and make sure the version >= 3.8.0 
print(sys.version)

# Install dependencies 
!{sys.executable} -m pip install meshio
!{sys.executable} -m pip install giotto-tda
!{sys.executable} -m pip install scikit-image
!{sys.executable} -m pip install pandas

3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0]
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable


You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.


The functions provided in this notebook allow for the easy visualization and comparison of homology classes by means of the representative cycles.

For each persistence pair of dimension 1 in the persistence diagram, there is a 1-cycle representing the boundary of the corresponding homology class. Persistence pairs and cycles can be accessed by reading the VTK files with `meshio`.

In [2]:
import meshio
ppairs = meshio.read("./data/vtk-original/0/3_pd.vtk")

The persistence diagram is stored as a collection of lines. 
Each line represents a persistence pair. The line end-points are geometrically located where the homology class was born/died.

For each line of index `i` we can access:
- the persistence value associated with the pair (`ppairs.cell_data["Persistence"][i]`)
- the dimension of the homology class (`ppairs.cell_data["Type"][i]`)
- the end-points of the line (`ppairs.cells[0].data[i][0]`,`ppairs.cells[0].data[i][1]`)


For each point of index `p` we can access:
- the dimension of the corresponding simplex (`ppairs.point_data["Type"][p]`)
- the filtration value (`ppairs.point_data["Filtration"][p]`)
- the point position in the original domain (`ppairs.points[p]`)

In [3]:
import meshio
cycle = meshio.read("./data/vtk-original/0/3_cycles.vtk")

Since we are analyzing 2D images, we only have 1-dimensional cycles to represent the homology class. Then, each cycle is stored as a collection of lines. 

For each line of index `i` we can access:
- the unique id of the cycle the edge belongs to (`cycle.cell_data["CycleId"][i]`). Moreover, the CycleID indicates the persistence pair corresponding to the cycle (`ppair.cell_data[cycle.cell_data["CycleId"][i]]`) 
- the persistence value associated to the persistence pair (`cycle.cell_data["Filtration][i]`)


In [4]:
import os
import meshio
import numpy as np
import pandas as pd
import gtda.diagrams as gdiagrams
import plotly.express as px
import plotly.graph_objs as gobj
from plotly.offline import init_notebook_mode, iplot
from skimage import io
from scipy import ndimage


DATA_DIR = os.path.join(os.getcwd(), "data")              # path of the data folder
IMG_DIR = os.path.join(DATA_DIR, "mnist_png")             # path of the image folder
VTK_DIR = os.path.join(DATA_DIR, "vtk-distancetransform") # path of the vtk files originated with the distance transform

init_notebook_mode(connected=True)

We have implemented two helper functions that can be used to extract information from these files:
- `getPersCycles()`: Extract information about the geometry of each cycle stored in a vtk file.
- `getPersDiagram()`: Create a persistence diagram starting from the persistence pairs stored in a vtk file.

In [5]:
def getPersCycles(cycleFile):
    """
    Get persistence cycles from the vtk file storing the persistence cycles.
    
    Parameters
    ----------
    cycleFile: string
        The path of the vtk file storing the persistence cycles.
    
    Returns
    ---------
    ordered_cycles: dict
        The dictionary storing the cycle information.
    """
    im = meshio.read(cycleFile)
    
    # for each cycle id, save the list of edges
    ordered_cycles = {}
    array_of_cycles = {}
    for i in range(len(im.cell_data['CycleId'][0])):
        index = str(im.cell_data['CycleId'][0][i])

        if(index not in array_of_cycles):
            array_of_cycles[index] = []


        line = im.cells_dict['line'][i]
        array_of_cycles[index].append([line[0].tolist(), line[1].tolist()])
    
    # inner function to search for the next point
    def searchNext(all_lines, visited, point, prev):
        for i in range(len(all_lines)):
            if(not visited[i]):
                line = all_lines[i]
                if(point == line[0] and prev != line[1]):
                    visited[i] = True
                    return line[1]
                elif(point == line[1] and prev != line[0]):
                    visited[i] = True
                    return line[0]
        
    # for each cycle reorder the vertices so to have them ready to be plotted with THREE.js
    for k in array_of_cycles:
        val = array_of_cycles[k]
        visited = np.zeros(len(val))
        new_array = []

        first_point= val[0][0]
        prevP = val[0][0]
        nextP = val[0][1]

        visited[0] = True

        new_array.append(im.points[first_point].tolist())
        while(nextP != first_point):
            new_array.append(im.points[nextP].tolist())
            newP = searchNext(val, visited, nextP, prevP)
            prevP = nextP
            nextP = newP

        new_array.append(im.points[first_point].tolist())
        ordered_cycles[k] = new_array
        
    return ordered_cycles    

In [6]:
def getPersDiagram(diagramFile):
    """
    Get persistence diagram pairs from the vtk file storing persistence diagram.
    
    Parameters
    ----------
    diagramFile: string
        The path of the diagram vtk file.
        
    Returns 
    ----------
    pdiagram: array
        The numpy array storing the persistence diagram in the form (birth, death, dimension).
    """
    pdiagram = []
    try: 
        ppairs = meshio.read(diagramFile)
        k = 0
        for line in ppairs.cells[0].data: 
            v0 = line[0]
            v1 = line[1]
            f0 = ppairs.point_data["Filtration"][v0]    # birth
            f1 = ppairs.point_data["Filtration"][v1]    # death
            t = ppairs.cell_data["Type"][0][k]          # homology dimension
            k += 1
            pdiagram.append([f0, f1, t])
    except:
        print("No persistence pairs in the file")
        
    return np.asarray(pdiagram)

The plotting functions use Plotly to visualize the information contained in the VTK files.

The first step is to visualize components and cycles alone. To do so, we have implemented two functions to overlay such information to the image of the digit used to generate them. The function uses the `Scatter` class form Plotly.

The first function, `visualizeComponents`, simply reads the persistence pairs from the persistence diagram and plots them in the original image domain. For each point, it also indicates their lifespan.

In [7]:
def visualizeComponents(img, diagramFile):
    """
        Plot persistence cycles on the original image file.

        Parameters
        ----------
        img: matrix
            The matrix storing the image. 
        diagramFile: string
            The path of the vtk file storing the persistence pairs.

        Returns
        ----------
        fig : :class:`plotly.graph_objects.Figure` object
            Figure showing where each component was born.
    """
    
    fig = px.imshow(img, color_continuous_scale='gray')

        
    ppairs = meshio.read(diagramFile)
    k = 0
    xcoords = []
    ycoords = []
    births = []
    deaths = []
    for line in ppairs.cells[0].data: 
        if(ppairs.cell_data["Type"][0][k] == 0):
            xcoords.append(ppairs.points[line[0]][1])
            ycoords.append(ppairs.points[line[0]][0])
            births.append(ppairs.point_data["Filtration"][line[0]])
            deaths.append(ppairs.point_data["Filtration"][line[1]])
    
    
    df = pd.DataFrame(data={"x":xcoords, "y":ycoords, "birth":births, "death":deaths})
    fig.add_trace(gobj.Scatter(x=df["x"], y=df["y"], text=df["death"]-df["birth"], hoverinfo="text", mode="markers"))
    
    head_tail = os.path.split(diagramFile)
    digit = head_tail[0][-1]
    filename = head_tail[1]
    fig.update_layout(height=400, width=400, title_text="Digit "+digit+" - Persistence Diagram file "+filename)
    fig.update_layout(coloraxis_showscale=False)
    fig.update_xaxes(showticklabels=False)
    fig.update_yaxes(showticklabels=False)
        
    
    return fig

With `visualizeComponets`, we can plot components over the original image,

In [8]:
digitPrefix = "0/10"
pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
img = io.imread(pngFile)

diagramFile = os.path.join(VTK_DIR, digitPrefix+"_pd.vtk")

iplot(visualizeComponents(img,diagramFile))

or over the filtration that originated the persistence pairs.

In [9]:
digitPrefix = "0/10"
pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
im = io.imread(pngFile)

inside = im > 0
outside = im <= 0

im1 = ndimage.morphology.distance_transform_edt(inside)
im2 = ndimage.morphology.distance_transform_edt(outside)

imf = im2-im1
imf = (imf - np.min(imf))/np.ptp(imf)

cycleFile = os.path.join(VTK_DIR, digitPrefix+"_pd.vtk")
iplot(visualizeComponents(imf, cycleFile))

The second function, `visualizeCycles`, uses a helper function `getPersCycles` to read the ordered sequence of vertices forming each cycle.

In [10]:
def visualizeCycles(img, cycleFile):
    """
    Plot persistence cycles on the original image file.
    
    Parameters
    ----------
    img: matrix
        The matrix storing the image. 
    cycleFile: string
        The path of the vtk file storing the persistence cycles.
    
    Returns
    ----------
    fig : :class:`plotly.graph_objects.Figure` object
        Figure showing the persistence cycles on top of the image file.
    """
    
    fig = px.imshow(img, color_continuous_scale='gray')
    
    try: 
        ordered_cycles = getPersCycles(cycleFile)
        coords = list(ordered_cycles.values())
        for cycle in coords:        
            flat_coords = np.asarray([item for item in cycle])
            fig.add_trace(gobj.Scatter(x=flat_coords[:,1], y=flat_coords[:,0], mode='lines'))
        
    except:
        print("No cycles to visualize!")
    
    # Adjust the properties of the figure
    head_tail = os.path.split(cycleFile)
    digit = head_tail[0][-1]
    filename = head_tail[1]
    
    fig.update_layout(height=400, width=400, title_text="Digit "+digit+" - Cycle file "+filename)
    fig.update_layout(coloraxis_showscale=False)
    fig.update_xaxes(showticklabels=False)
    fig.update_yaxes(showticklabels=False)
    
    return fig


Also in this case, `visualizeCycles` accepts an image as input. This can be used to visualize cycles over the original image,

In [11]:
digitPrefix = "8/110"
pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
img = io.imread(pngFile)

cycleFile = os.path.join(VTK_DIR, digitPrefix+"_cycles.vtk")
iplot(visualizeCycles(img, cycleFile))

or over the filtration that originated the cycles.

In [12]:
digitPrefix = "8/110"
pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
im = io.imread(pngFile)

inside = im > 0
outside = im <= 0

im1 = ndimage.morphology.distance_transform_edt(inside)
im2 = ndimage.morphology.distance_transform_edt(outside)

imf = im2-im1
imf = (imf - np.min(imf))/np.ptp(imf)

cycleFile = os.path.join(VTK_DIR, digitPrefix+"_cycles.vtk")
iplot(visualizeCycles(imf, cycleFile))

# 3. Applications

Here we provide two examples where the direct visualization of cycles can be helpful.

## 3.1. Definition of the most suitable filtration

The first scenario where the direct visualization of cycles could be useful is when we need to decide a suitable filtration for the input data. In general, we would like to use the best filtration to capture interesting features with persistence pairs. Different filtrations will lead to different features, and thus the natural question arising is "What filtration should I choose?". The direct visualization of cycles can help with our choice.

For example, considering the MNIST dataset, we may decide whether to filter each input image according to the original pixel values, or the opposite order, or new images derived from the original ones (e.g., distance transform).

![filtrations](pictures/filtrations.png)

In this example, we pick one of the digit files encoding the digit `8`.

In [13]:
digitPrefix = "8/110"

We can visualize the generated cycles when the filtration is selected to be defined by the original pixel values.

In [14]:
VTK_DIR_ORIG = os.path.join(DATA_DIR, "vtk-original") 

pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
img = io.imread(pngFile)
cycleFile = os.path.join(VTK_DIR_ORIG, digitPrefix+"_cycles.vtk")

iplot(visualizeCycles(img, cycleFile))

The same process can be repeated on negating the original pixel values.

In [15]:
VTK_DIR_INV = os.path.join(DATA_DIR, "vtk-inverse")

pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
img = io.imread(pngFile)
cycleFile = os.path.join(VTK_DIR_INV, digitPrefix+"_cycles.vtk")

iplot(visualizeCycles(img, cycleFile))

And finally apply the filtration using the distance transform.

In [16]:
pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
img = io.imread(pngFile)
cycleFile = os.path.join(VTK_DIR, digitPrefix+"_cycles.vtk")

iplot(visualizeCycles(img, cycleFile))

As we can notice, the filtration based on the origina pixel values is not highlighting the features of the input digit. In this case, the filtration starts from the dark pixels and creates a large cycle (i.e., `trace 6`) which is later broken in smaller cycles as soon as more pixels are introduced.

The filtration based on the inverse of the original pixel values does a better job at localizing the two loops in the digit `8`, but many other cycles are created due to the noise in the input image.

The filtration based on the distance transform is similar to the previous one but less noisy, and thus generates fewer cycles.

Regardless of our final choice, the direct visualization of the cycles can help us deciding which one is the best filtration for the features we would like to recognize in our input data.

## 3.2. Unsupervised analysis with topological features

As another example where visualizing cycles could be of help, we consider the unsupervised analysis of data by means of TDA descriptors. 

For each input image in the MNIST dataset, we compute a descriptor called `PersistenceImage`. We used the function provided by [Giotto-TDA](https://giotto-ai.github.io/gtda-docs/0.2.1/modules/generated/diagrams/representations/gtda.diagrams.PersistenceImage.html) at first, but we experienced some issue with getting the correct persistence image when there is only 1 persistence pair in the diagram. 

Therefore, we have modified the function by adapting the `_bin()` function from `gtda.diagrams._utils` with manually setting the minimum and maximum values used to generate the bins for the diagram. Since the function is called in the `fit()` function of the `PersistenceImage` class, we have also modified the `fit()` function as follows.

In [17]:
from gtda.diagrams._utils import _subdiagrams, _sample_image, _homology_dimensions_to_sorted_ints

def bins(X, metric, n_bins=100, homology_dimensions=None, **kw_args):
    if homology_dimensions is None:
        homology_dimensions = sorted(np.unique(X[0, :, 2]))
    # For some vectorizations, we force the values to be the same + widest
    sub_diags = {dim: _subdiagrams(X, [dim], remove_dim=True)
                 for dim in homology_dimensions}
    # For persistence images, move into birth-persistence
    if metric == 'persistence_image':
        for dim in homology_dimensions:
            sub_diags[dim][:, :, [1]] = sub_diags[dim][:, :, [1]] \
                - sub_diags[dim][:, :, [0]]
    
    # Here we changed the approach for getting minimum and maximum values
    min_vals = {dim: np.asarray([0, 0])
                for dim in homology_dimensions}
    max_vals = {dim: np.max(sub_diags[dim], axis=(0, 1))
                for dim in homology_dimensions}
    # max_vals = {dim: np.asarray([1, 1])
    #           for dim in homology_dimensions}

    
    if metric in ['landscape', 'betti', 'heat', 'silhouette']:
        #  Taking the min(resp. max) of a tuple `m` amounts to extracting
        #  the birth (resp. death) value
        min_vals = {d: np.array(2*[np.min(m)]) for d, m in min_vals.items()}
        max_vals = {d: np.array(2*[np.max(m)]) for d, m in max_vals.items()}

    # Scales between axes should be kept the same, but not between dimension
    all_max_values = np.stack(list(max_vals.values()))
    if len(homology_dimensions) == 1:
        all_max_values = all_max_values.reshape(1, -1)
    global_max_val = np.max(all_max_values, axis=0)
    max_vals = {dim: np.array([max_vals[dim][k] if
                               (max_vals[dim][k] != min_vals[dim][k])
                               else global_max_val[k] for k in range(2)])
                for dim in homology_dimensions}
    
    samplings = {}
    step_sizes = {}
    for dim in homology_dimensions:
        samplings[dim], step_sizes[dim] = np.linspace(
            min_vals[dim], max_vals[dim], retstep=True, num=n_bins)
    if metric in ['landscape', 'betti', 'heat', 'silhouette']:
        for dim in homology_dimensions:
            samplings[dim] = samplings[dim][:, [0], None]
            step_sizes[dim] = step_sizes[dim][0]
    return samplings, step_sizes


def fit(pimgObj, X):
    if pimgObj.weight_function is None:
        pimgObj.effective_weight_function_ = np.ones_like
    else:
        pimgObj.effective_weight_function_ = pimgObj.weight_function

    # Find the unique homology dimensions in the 3D array X passed to `fit`
    # assuming that they can all be found in its zero-th entry
    homology_dimensions_fit = np.unique(X[0, :, 2])
    pimgObj.homology_dimensions_ = \
        _homology_dimensions_to_sorted_ints(homology_dimensions_fit)
    pimgObj._n_dimensions = len(pimgObj.homology_dimensions_)

    pimgObj._samplings, pimgObj._step_size = bins(
        X, "persistence_image",  n_bins=pimgObj.n_bins,
        homology_dimensions=pimgObj.homology_dimensions_
        )
    pimgObj.weights_ = {
        dim: pimgObj.effective_weight_function_(samplings_dim[:, 1])
        for dim, samplings_dim in pimgObj._samplings.items()
        }
    pimgObj.samplings_ = {dim: s.T for dim, s in pimgObj._samplings.items()}

We now use the new functions to compute the persistence images for the dataset.

In [18]:
def getPersImage(diagramFile, dimension=None, plot=False):
    """
    Get persistence image from the vtk file storing persistence diagram.
    
    Parameters
    ----------
    diagramFile: string
        The path of the diagram vtk file.
    dimensions: int
        The homology dimension.
    plot: bool
        If True, plot the computed persistence image.
        
    Returns 
    ----------
    persImage: array
        The numpy array storing the persistence image.
    """
    num_pixels = 10
    pdiagram = getPersDiagram(diagramFile)
    if pdiagram.size == 0:
        return np.zeros((num_pixels, num_pixels))
    pdiagram3D = pdiagram.reshape(1, -1, 3)
    
    pimgr = gdiagrams.PersistenceImage(sigma=0.1, n_bins=num_pixels)
    fit(pimgr, pdiagram3D)
    persImage = pimgr.transform(pdiagram3D)
    
    if dimension is None: 
        if plot:
            pimgr.plot(persImage)
        return persImage[0]
    
    if dimension >= persImage.shape[1]:
        return np.zeros((num_pixels, num_pixels))
    
    if plot:
        fig = pimgr.plot(persImage, homology_dimension_idx=dimension)
        fig.show()
    return persImage[0][dimension]
    

persImages = []
fileLabels = []
for i in range(10):
    pdiagDir = os.path.join(VTK_DIR, str(i))
    if os.path.exists(pdiagDir):
        files = [f for f in os.listdir(pdiagDir) if "_pd.vtk" in f]
        files.sort()
        for file in files:
            filePath = os.path.join(pdiagDir, file)
            persImages.append(getPersImage(filePath, 1))
            fileLabels.append(str(i) + '/' + file)


No persistence pairs in the file
No persistence pairs in the file


Each persistence image is then vectorized and used as a high-dimensional descriptor of the input image. To explore the similarity and difference among these descriptors, we use t-SNE to generate lower dimensional embeddings for such descriptors.

In [19]:
import scipy.spatial.distance as ssdist
from sklearn import manifold
from sklearn.metrics import pairwise_distances

def getEmbeddings(persImages):
    """
    Generate the embeddings from the high-dimensional data using t-SNE method.

    Parameters
    ----------
    persImage: array_like
        The array storing persistence images of same size.
    
    Returns
    ----------
    embeddings: ndarray 
        The array containing embeddings computed with t-SNE.
    """
    pers_images = np.asarray(persImages)
    if pers_images.ndim != 3:
        print("The dimension of the input array should be 3!\n")
        return -1
    
    pers_images = pers_images.reshape(len(pers_images), -1)
    tSNEMethod = manifold.TSNE(n_components=2, init="pca", random_state=0)
    embeddings = tSNEMethod.fit_transform(pers_images)
    
    return embeddings

digitLabels = [f[0] for f in fileLabels]
Y = getEmbeddings(persImages)
# plot the scattering 
df = pd.DataFrame(data={"x":Y[:,0], "y":Y[:,1], "digit": digitLabels, "file": fileLabels})
embeddingPlot = px.scatter(df, x="x", y="y", color="digit", hover_data=["x", "y", "file"])
iplot(embeddingPlot)

The lower dimensional embedding provides information regarding possible groups. In this case, since we are using descriptors based on 1-cycles only, the main difference captured by t-SNE relates to the number of cycles found in each filtration.

At this point, natural questions may arise like: "why two points are close/far away in the 2D plot". Cycles can help answer these questions by providing an explicit representation of the homology classes that contribute to each persistence image.


### Cluster with 2 major cycles

![scaled plot 1](./pictures/plot_example_1.png)

The figure above shows the scaled view of the bottom right part of the embedding plot, where most digits are `8` with two cycles. To understand why some digits with 1 cycle appear in the cluster, we picked three example points from the figure:

- the digit `3` in purple which is associated with the file `3/18_pd.vtk`, 
- the digit `6` in coral pink which is associated with the file `6/366_pd.vtk`, 
- the digit `8` in pink which is associated with the file `8/401_pd.vtk`. 

We can then visualize the cycle information from the corresponding cycle vtk files. 

In [20]:
digitList = ["8/401", "3/18", "6/366"]

for digitPrefix in digitList:
    pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
    im = io.imread(pngFile)
    
    inside = im > 0
    outside = im <= 0

    im1 = ndimage.morphology.distance_transform_edt(inside)
    im2 = ndimage.morphology.distance_transform_edt(outside)

    imf = im2-im1
    imf = (imf - np.min(imf))/np.ptp(imf)

    cycleFile = os.path.join(VTK_DIR, digitPrefix+"_cycles.vtk")
    iplot(visualizeCycles(imf, cycleFile))

From the images above, we can see that applying the distance transform to the files encoding digits `3` and `6` creates two undesired cycles, which makes them accidently clustered with the group of the digit `8`. 

### Cluster without any major cycles

![scaled plot 2](./pictures/plot_example_2.png)

The figure above shows the scaled view of the leftmost part of the embedding plot, where most digits are without any cycles. To understand why some digits with 1 cycle appear in the cluster, we picked three example points: 

- the digit `2` in green which is associated with the file `2/208_pd.vtk` (expected to have no cycles), 
- the digit `6` in coral pink which is associated with the file `6/559_pd.vtk` (expected to have one major cycle),  
- the digit `9` in yellow which is associated with the file `9/20_pd.vtk` (expected to have one major cycle). 

We can then visualize the cycle information from the corresponding vtk files. 

In [21]:
digitList = ["2/208", "6/559", "9/20"]

for digitPrefix in digitList:
    pngFile = os.path.join(IMG_DIR, digitPrefix+".png")
    im = io.imread(pngFile)
    
    inside = im > 0
    outside = im <= 0

    im1 = ndimage.morphology.distance_transform_edt(inside)
    im2 = ndimage.morphology.distance_transform_edt(outside)

    imf = im2-im1
    imf = (imf - np.min(imf))/np.ptp(imf)

    cycleFile = os.path.join(VTK_DIR, digitPrefix+"_cycles.vtk")
    iplot(visualizeCycles(imf, cycleFile))

No cycles to visualize!


From the images above, we can see that no major cycles are deteced in these digits if we use the distance transform. This is the reason why they end up in the same cluster.

# 4. Benchmark


Our apprach uses Discrete Morse Theory to encode the original chain complex by means of a Forman gradient. In practice, this allows for a more compact encoding of the information normally contained in the boundary matrix. Everything is implemented in plain C++ and integrated in the [TTK library](https://topology-tool-kit.github.io/).

The steps for computing persistent homology with our modules are as follows:

1. triangulate the input image (feature provided by [TTK](https://github.com/topology-tool-kit/ttk/tree/dev/core/vtk/ttkTriangulationReader))
2. compute the Forman gradient according to the algorithm by [Robins et al., 2011](https://ieeexplore.ieee.org/document/5766002) (implemented [here](https://github.com/IuricichF/PersistenceCycles/tree/main/ttk-0.9.7/core/base/formanGradient))
3. compute the chain complex represented by the Forman gradient (implemented [here](https://github.com/IuricichF/PersistenceCycles/blob/b68ae3ebc218ed69babeee5c1e4ac7f5a89564cd/ttk-0.9.7/core/base/fG_PersistentHomology/FG_PersistentHomology_template.h#L37))
4. use the standard algorithm to compute persitent homology on the chain complex (implemented [here](https://github.com/IuricichF/PersistenceCycles/tree/main/ttk-0.9.7/core/base/boundaryMatrix))
5. for each pair reconstruct the cycle (implemented [here](https://github.com/IuricichF/PersistenceCycles/blob/b68ae3ebc218ed69babeee5c1e4ac7f5a89564cd/ttk-0.9.7/core/base/fG_PersistentHomology/FG_PersistentHomology_template.h#L318))

The method turns out to be very efficient, even if we are just interested in computing persistent homology. With a large image (a 3D image of size [500x500x100]), the computation of persistent homology takes 66.5 seconds and 1.09GB of memory using 48 threads on a desktop computer with two 3.00GHz Intel Xeon 6136 CPUs and 64GB of memory. As a comparison, [DIPHA](https://github.com/DIPHA/dipha) requires 69.4 seconds and 29.7GB on the same machine.


Mapping information from the persistent diagram back to the original domain is a feature rarely offered by TDA packages. In part, this is due to the algorithms used to speedup persistent homology computation. Since they distrupt the information contained in the boundary matrix, it becomes impossible to reconstruct the cycles.

Finding the location of the simplices responsible for the birth or death of an homology class is a simpler task. To the best of our knowledge only [TTK](https://topology-tool-kit.github.io/index.html) and [HomCloud](https://homcloud.dev/basic-usage.en.html) provide such features.

Regarding the computation of cycles, [Eeirene](https://github.com/Eetion/Eirene.jl), a package developed in Julia, provides the computation of representative cycles when working on Vietoris-Rips filtrations or point clouds only.

# 5. Limitations and Perspectives

## Limitations of our method

To build up our notebook, we had to compute persistence diagrams and corresponding cycles outside of Giotto-TDA. This is because we needed persistence pairs to be aligned with the computed cycles.

Our currenet implementation presents some limitation since it is designed to work with simplicial complexes up to dimension 3 only. This includes triangle meshes, tetrahedral meshes, or 2D and 3D images that are automatically triangulated by TTK.

## Limitations of Giotto-TDA

One problem we encountered with Giotto-TDA was computing persistence images on persistence diagrams formed by a single persistence pair. As the example shown below, we get an empty persistence image when there is only one persistence pair. 


In [22]:
exampleDiagram = np.array([[[0.1, 0.2, 1]]])
pimgr = gdiagrams.PersistenceImage(sigma=0.01, n_bins=10)
pimgr.fit(exampleDiagram)
persImage = pimgr.transform(exampleDiagram)
print(persImage)
iplot(pimgr.plot(persImage[0]))

[[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]]


The root cause of the problem is in the `_bin()` function from `gtda.diagrams._utils`, and specifically the code to find the minimum and maximum persistence pair from the persistence diagram for generating the sampling slices and step sizes.

```python
def _bin(X, metric, n_bins=100, homology_dimensions=None, **kw_args):
    # ......
    min_vals = {dim: np.min(sub_diags[dim], axis=(0, 1))
                for dim in homology_dimensions}
    max_vals = {dim: np.max(sub_diags[dim], axis=(0, 1))
                for dim in homology_dimensions}
    # ......
    samplings = {}
    step_sizes = {}
    for dim in homology_dimensions:
        samplings[dim], step_sizes[dim] = np.linspace(
            min_vals[dim], max_vals[dim], retstep=True, num=n_bins
            )
        
    # ......
```

One possible fix would be to add a parameter for `PersistenceImage` class which allows to manually set the range, so that it can be used in the `_bin()` function. As a comparison, we provide the persistence image generated with this approach.

In [23]:
exampleDiagram = np.array([[[0.1, 0.2, 1]]])
pimgr = gdiagrams.PersistenceImage(sigma=0.01, n_bins=10)
fit(pimgr, exampleDiagram)
persImage = pimgr.transform(exampleDiagram)
with np.printoptions(precision=2, suppress=True, linewidth=np.inf):
    print(persImage)
iplot(pimgr.plot(persImage))

[[[[   0.      0.      0.      0.      0.      0.08    6.15  134.74  858.49 1591.55]
   [   0.      0.      0.      0.      0.      0.04    3.32   72.68  463.08  858.49]
   [   0.      0.      0.      0.      0.      0.01    0.52   11.41   72.68  134.74]
   [   0.      0.      0.      0.      0.      0.      0.02    0.52    3.32    6.15]
   [   0.      0.      0.      0.      0.      0.      0.      0.01    0.04    0.08]
   [   0.      0.      0.      0.      0.      0.      0.      0.      0.      0.  ]
   [   0.      0.      0.      0.      0.      0.      0.      0.      0.      0.  ]
   [   0.      0.      0.      0.      0.      0.      0.      0.      0.      0.  ]
   [   0.      0.      0.      0.      0.      0.      0.      0.      0.      0.  ]
   [   0.      0.      0.      0.      0.      0.      0.      0.      0.      0.  ]]]]


## Perspectives


We think it would be very useful to integrate our module in Giotto-tda. While we have not taken steps in this directions yet, the integration should not be too challenging. 

Regarding the input, we should adapt TTK Triangulation so to let it read and triangulate a numpy array. Regarding outputs, we can simply convert persistence diagrams in the format generated by Giotto-TDA and define a new object to store cycles.

Aside from adapting our implementation, we should also design visualization functions for 2-cycles in 3D. In practice, these are surfaces representing the boundary of the voids created by the filtration. This type of visualizations should be doable and can be fairly easy to achieve with Plotly.